/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */
import type { CollectionIdsParameter } from "./collectionIdsParameter";

export type GetListParams = { collection_ids?: CollectionIdsParameter };
