/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */
import type { CollectionIdsParameter } from "./collectionIdsParameter";

export type GetListParams = {
  /**
   * Filter the list reply down to the given collection identifiers. This is the recommended way to check for existence of multiple collections on the list.
   */
  collection_ids?: CollectionIdsParameter;
};
