/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */

/**
 * A collection identifier in the form <digits>-<alphanum>:<alphanum>.
 */
export type ItemId = string;
