/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */

/**
 * A collection identifier in the form <digits>-<alphanum>:<alphanum>.
 * @pattern ^\d+-\w+:\w+$
 */
export type ItemId = string;
