/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Collection List
 * OpenAPI spec version: 2.0.0
 */

/**
 * List identifier. In the initial version, this can only be "default".
 */
export type ListId = string;
