/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DDF Cover Service
 * This service provides covers for library materials indexed by isbn, issn, faust, pid.
The service is provided by [Det Digitale Folkebibliotek](https://detdigitalefolkebibliotek.dk/section/i-brug-paa-biblioteket/cover-service)
### Authentication notes
Authentication is done via OAuth2 against auth.dbc.dk. To obtain a valid token follow the instructions here: [Open Platform](https://openplatform.dbc.dk/v3/). To use the "Authorize" option in this tool use your 'client_id' and 'client_secret' and fill in '@agency' (e.g. '@123456') for both username and password.
 * OpenAPI spec version: 2.0
 */
import type { GetCoverCollectionType } from "./getCoverCollectionType";
import type { GetCoverCollectionSizesItem } from "./getCoverCollectionSizesItem";

export type GetCoverCollectionParams = {
  /**
   * The type of the identifier, i.e. 'isbn', 'faust', 'pid' or 'issn'
   */
  type: GetCoverCollectionType;
  /**
   * A list of identifiers of {type}. Maximum number os identifiers per reqeust is 200
   */
  identifiers: string[];
  /**
 * A list of image sizes for the cover(s) you want to receive. Please note:
  - If the cover is not available for the requested size 'null' will be returned for that size.
  - If the 'sizes' parameter is omitted the 'default' size will be returned,
  - If you request the 'original' size a cover will always be returned.

 The different sizes in pixels (height).
  - default: 1000px
  - original: [variable]
  - xx-small: 104px
  - x-small: 136px
  - small: 160px
  - small-medium: 230px
  - medium: 270px
  - medium-large: 430px
  - large: 540px
 */
  sizes?: GetCoverCollectionSizesItem[];
};
