version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Copenhagen
    labels:
      - dependencies
      - github_actions
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Copenhagen
    versioning-strategy: increase
    labels:
      - dependencies
    groups:
      babel:
        patterns:
          - "@babel/*"
      fullcalendar:
        patterns:
          - "@fullcalendar/*"
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
          - "@graphql-typed-document-node/core"
          - "replace-in-file"
          - "typescript-graphql-typed-files-modules"
      react:
        patterns:
          - "react"
          - "@types/react"
          - "react-dom"
          - "@types/react-dom"
      redux:
        patterns:
          - "@reduxjs/toolkit"
          - "@types/react-redux"
          - "react-redux"
          - "redux"
          - "redux-persist"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      testing-library:
        patterns:
          - "@testing-library/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-config-prettier"
          - "eslint-loader"
          - "eslint-plugin-cypress"
          - "eslint-plugin-import"
          - "eslint-plugin-jsx-a11y"
          - "eslint-plugin-no-only-tests"
          - "eslint-plugin-prettier"
          - "eslint-plugin-react"
          - "eslint-plugin-react-hooks"
          - "eslint-webpack-plugin"
          - "@eslint/*"
      cypress:
        patterns:
          - "cypress"
          - "@cypress/*"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "storybook"
        versions: [">=9"]
      - dependency-name: "@storybook/react-webpack5"
        versions: [">=9"]
      - dependency-name: "@chromatic-com/storybook"
        versions: [">=4"]
      - dependency-name: "dotenv"
        update-types: ["version-update:semver-major"]
      - dependency-name: "happy-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "caniuse-lite"
        versions: [">=1.0.30001741"]
      - dependency-name: "@types/react"
        versions: [">=19.1.13"]
      - dependency-name: "eslint-plugin-react-hooks"
        update-types: ["version-update:semver-major"]
