version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - dependencies
      - github_actions
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - dependencies
    groups:
      babel:
        patterns:
          - "@babel/*"
      fullcalendar:
        patterns:
          - "@fullcalendar/*"
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
          - "@graphql-typed-document-node/core"
          - "replace-in-file"
          - "typescript-graphql-typed-files-modules"
      react:
        patterns:
          - "react"
          - "@types/react"
          - "react-dom"
          - "@types/react-dom"
      redux:
        patterns:
          - "@reduxjs/toolkit"
          - "@types/react-redux"
          - "react-redux"
          - "redux"
          - "redux-persist"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      testing-library:
        patterns:
          - "@testing-library/*"
