version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - dependencies
      - github_actions
    reviewers:
      - Adammik10
      - kasperbirch1
      - kasperg
      - spaceo
  - package-ecosystem: yarn
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    target-branch: v5
    labels:
      - dependencies
    reviewers:
      - Adammik10
      - kasperbirch1
      - kasperg
      - spaceo
