version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - dependencies
      - github_actions
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      timezone: Europe/Copenhagen
    labels:
      - dependencies
    groups:
      babel:
        patterns:
          - "@babel/*"
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
      storybook:
        patterns:
          - "@storybook/*"
