version: '3'
services:
  node:
    environment:
      VIRTUAL_HOST: ddb-react.docker
      VIRTUAL_PORT: 80
      CHOKIDAR_USEPOLLING: 1
volumes:
  root:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
