/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type ProxyUrlGETFormat =
  typeof ProxyUrlGETFormat[keyof typeof ProxyUrlGETFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProxyUrlGETFormat = {
  json: "json"
} as const;
