/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type ProxyUrlGET400 = {
  error?: string;
};
