import { Factory } from "fishery";
import type { Manifestation } from "../../src/core/dbc-gateway/generated/graphql";
import { creatorFactory } from "./creator.factory";

export const manifestationFactory = Factory.define<Manifestation>(() => ({
  __typename: "Manifestation",
  pid: "870970-basis:52557240",
  abstract: [],
  access: [],
  accessTypes: [],
  audience: null,
  catalogueCodes: {
    __typename: "CatalogueCodes",
    nationalBibliography: [],
    otherCatalogues: []
  },
  cataloguedPublicationStatus: null,
  classifications: [],
  contents: null,
  contributors: [],
  contributorsFromDescription: [],
  cover: {
    __typename: "Cover",
    detail: null,
    detail42: null,
    detail117: null,
    detail207: null,
    detail500: null,
    large: null,
    medium: null,
    origin: null,
    small: null,
    thumbnail: null,
    xSmall: null
  },
  creators: [creatorFactory.build()],
  creatorsFromDescription: [],
  dateFirstEdition: null,
  edition: null,
  fictionNonfiction: null,
  genreAndForm: ["roman", "slægtsromaner"],
  hostPublication: null,
  identifiers: [],
  languages: null,
  latestPrinting: null,
  localId: null,
  manifestationParts: null,
  marc: null,
  materialTypes: [],
  notes: [],
  ownerWork: {
    __typename: "Work",
    workId: "work-id",
    abstract: [],
    genreAndForm: [],
    materialTypes: [],
    creators: [],
    titles: {
      __typename: "WorkTitles",
      full: ["De syv søstre : Maias historie"],
      main: ["De syv søstre"],
      original: ["The seven sisters"],
      parallel: [],
      sort: "De syv søstre",
      standard: null,
      titlePlusLanguage: null,
      translated: null,
      tvSeries: null
    },
    fictionNonfiction: null,
    subjects: {
      __typename: "SubjectContainer",
      all: [],
      dbcVerified: []
    },
    dk5MainEntry: null,
    mainLanguages: [],
    workTypes: [],
    workYear: null,
    relations: {
      __typename: "Relations",
      continuedIn: [],
      continues: [],
      discussedIn: [],
      discusses: [],
      hasAdaptation: [],
      hasAnalysis: [],
      hasCreatorDescription: [],
      hasDescriptionFromPublisher: [],
      hasManuscript: [],
      hasReusedReview: [],
      hasReview: [],
      hasSoundtrack: [],
      hasTrack: [],
      isAdaptationOf: [],
      isAnalysisOf: [],
      isDescriptionFromPublisherOf: [],
      isManuscriptOf: [],
      isPartOfAlbum: [],
      isPartOfManifestation: [],
      isReusedReviewOf: [],
      isReviewOf: [],
      isSoundtrackOfGame: [],
      isSoundtrackOfMovie: []
    },
    manifestations: {
      __typename: "Manifestations",
      all: [],
      bestRepresentation: {} as any,
      bestRepresentations: [],
      first: {} as any,
      latest: {} as any,
      mostRelevant: [],
      searchHits: null
    },
    series: [],
    universes: [],
    traceId: "work-trace-id"
  },
  physicalDescription: null,
  publisher: [],
  recordCreationDate: "2021-01-01",
  relatedPublications: [],
  relations: {
    __typename: "Relations",
    continuedIn: [],
    continues: [],
    discussedIn: [],
    discusses: [],
    hasAdaptation: [],
    hasAnalysis: [],
    hasCreatorDescription: [],
    hasDescriptionFromPublisher: [],
    hasManuscript: [],
    hasReusedReview: [],
    hasReview: [],
    hasSoundtrack: [],
    hasTrack: [],
    isAdaptationOf: [],
    isAnalysisOf: [],
    isDescriptionFromPublisherOf: [],
    isManuscriptOf: [],
    isPartOfAlbum: [],
    isPartOfManifestation: [],
    isReusedReviewOf: [],
    isReviewOf: [],
    isSoundtrackOfGame: [],
    isSoundtrackOfMovie: []
  },
  review: null,
  series: [],
  sheetMusicCategories: null,
  shelfmark: null,
  source: ["Bibliotekskatalog"],
  subjects: {
    __typename: "SubjectContainer",
    all: [],
    dbcVerified: []
  },
  tableOfContents: null,
  titles: {
    __typename: "ManifestationTitles",
    alternative: [],
    full: ["De syv søstre : Maias historie"],
    identifyingAddition: null,
    main: ["De syv søstre"],
    original: ["The seven sisters"],
    parallel: [],
    sort: "De syv søstre",
    standard: null,
    titlePlusLanguage: null,
    translated: null,
    tvSeries: null
  },
  traceId: "traceId",
  unit: null,
  universes: [],
  volume: null,
  workTypes: [],
  workYear: null
}));
