import { Factory } from "fishery";
import type { Work } from "../../src/core/dbc-gateway/generated/graphql";
import {
  FictionNonfictionCodeEnum,
  GeneralMaterialTypeCodeEnum,
  WorkTypeEnum
} from "../../src/core/dbc-gateway/generated/graphql";
import { creatorFactory } from "./creator.factory";

export const workFactory = Factory.define<Work>(() => ({
  __typename: "Work",
  workId: "work-of:870970-basis:52557240",
  abstract: [
    "Pa Salt dør og hans seks adoptivdøtre står tilbage med muligheden for at finde deres ophav."
  ],
  creators: [creatorFactory.build()],
  dk5MainEntry: null,
  fictionNonfiction: {
    __typename: "FictionNonfiction",
    display: "skønlitteratur",
    code: FictionNonfictionCodeEnum.Fiction
  },
  genreAndForm: ["roman", "slægtsromaner", "romaner"],
  latestPublicationDate: null,
  mainLanguages: [
    {
      __typename: "Language",
      display: "dansk",
      iso639Set1: "da",
      iso639Set2: "dan",
      isoCode: "dan"
    }
  ],
  manifestations: {
    __typename: "Manifestations",
    all: [],
    bestRepresentation: {
      __typename: "Manifestation",
      pid: "870970-basis:52557240",
      abstract: [],
      access: [],
      accessTypes: [],
      audience: null,
      catalogueCodes: {
        __typename: "CatalogueCodes",
        nationalBibliography: [],
        otherCatalogues: []
      },
      cataloguedPublicationStatus: null,
      classifications: [],
      contents: null,
      contributors: [],
      contributorsFromDescription: [],
      cover: {
        __typename: "Cover",
        detail: null,
        detail42: null,
        detail117: null,
        detail207: null,
        detail500: null,
        large: null,
        medium: null,
        origin: null,
        small: null,
        thumbnail: null,
        xSmall: null
      },
      creators: [],
      creatorsFromDescription: [],
      dateFirstEdition: null,
      edition: null,
      fictionNonfiction: null,
      genreAndForm: [],
      hostPublication: null,
      identifiers: [],
      languages: null,
      latestPrinting: null,
      localId: null,
      manifestationParts: null,
      marc: null,
      materialTypes: [],
      notes: [],
      ownerWork: {} as any,
      physicalDescription: null,
      publisher: [],
      recordCreationDate: "2021-01-01",
      relatedPublications: [],
      relations: {
        __typename: "Relations",
        continuedIn: [],
        continues: [],
        discussedIn: [],
        discusses: [],
        hasAdaptation: [],
        hasAnalysis: [],
        hasCreatorDescription: [],
        hasDescriptionFromPublisher: [],
        hasManuscript: [],
        hasReusedReview: [],
        hasReview: [],
        hasSoundtrack: [],
        hasTrack: [],
        isAdaptationOf: [],
        isAnalysisOf: [],
        isDescriptionFromPublisherOf: [],
        isManuscriptOf: [],
        isPartOfAlbum: [],
        isPartOfManifestation: [],
        isReusedReviewOf: [],
        isReviewOf: [],
        isSoundtrackOfGame: [],
        isSoundtrackOfMovie: []
      },
      review: null,
      series: [],
      sheetMusicCategories: null,
      shelfmark: null,
      source: [],
      subjects: {
        __typename: "SubjectContainer",
        all: [],
        dbcVerified: []
      },
      tableOfContents: null,
      titles: {
        __typename: "ManifestationTitles",
        alternative: [],
        full: [],
        identifyingAddition: null,
        main: [],
        original: null,
        parallel: [],
        sort: "",
        standard: null,
        titlePlusLanguage: null,
        translated: null,
        tvSeries: null
      },
      traceId: "traceId",
      unit: null,
      universes: [],
      volume: null,
      workTypes: [],
      workYear: null
    },
    bestRepresentations: [],
    first: {
      __typename: "Manifestation",
      pid: "870970-basis:52557240",
      abstract: [],
      access: [],
      accessTypes: [],
      audience: null,
      catalogueCodes: {
        __typename: "CatalogueCodes",
        nationalBibliography: [],
        otherCatalogues: []
      },
      cataloguedPublicationStatus: null,
      classifications: [],
      contents: null,
      contributors: [],
      contributorsFromDescription: [],
      cover: {
        __typename: "Cover",
        detail: null,
        detail42: null,
        detail117: null,
        detail207: null,
        detail500: null,
        large: null,
        medium: null,
        origin: null,
        small: null,
        thumbnail: null,
        xSmall: null
      },
      creators: [],
      creatorsFromDescription: [],
      dateFirstEdition: null,
      edition: null,
      fictionNonfiction: null,
      genreAndForm: [],
      hostPublication: null,
      identifiers: [],
      languages: null,
      latestPrinting: null,
      localId: null,
      manifestationParts: null,
      marc: null,
      materialTypes: [],
      notes: [],
      ownerWork: {} as any,
      physicalDescription: null,
      publisher: [],
      recordCreationDate: "2021-01-01",
      relatedPublications: [],
      relations: {
        __typename: "Relations",
        continuedIn: [],
        continues: [],
        discussedIn: [],
        discusses: [],
        hasAdaptation: [],
        hasAnalysis: [],
        hasCreatorDescription: [],
        hasDescriptionFromPublisher: [],
        hasManuscript: [],
        hasReusedReview: [],
        hasReview: [],
        hasSoundtrack: [],
        hasTrack: [],
        isAdaptationOf: [],
        isAnalysisOf: [],
        isDescriptionFromPublisherOf: [],
        isManuscriptOf: [],
        isPartOfAlbum: [],
        isPartOfManifestation: [],
        isReusedReviewOf: [],
        isReviewOf: [],
        isSoundtrackOfGame: [],
        isSoundtrackOfMovie: []
      },
      review: null,
      series: [],
      sheetMusicCategories: null,
      shelfmark: null,
      source: [],
      subjects: {
        __typename: "SubjectContainer",
        all: [],
        dbcVerified: []
      },
      tableOfContents: null,
      titles: {
        __typename: "ManifestationTitles",
        alternative: [],
        full: [],
        identifyingAddition: null,
        main: [],
        original: null,
        parallel: [],
        sort: "",
        standard: null,
        titlePlusLanguage: null,
        translated: null,
        tvSeries: null
      },
      traceId: "traceId",
      unit: null,
      universes: [],
      volume: null,
      workTypes: [],
      workYear: null
    },
    latest: {
      __typename: "Manifestation",
      pid: "870970-basis:52557240",
      abstract: [],
      access: [],
      accessTypes: [],
      audience: null,
      catalogueCodes: {
        __typename: "CatalogueCodes",
        nationalBibliography: [],
        otherCatalogues: []
      },
      cataloguedPublicationStatus: null,
      classifications: [],
      contents: null,
      contributors: [],
      contributorsFromDescription: [],
      cover: {
        __typename: "Cover",
        detail: null,
        detail42: null,
        detail117: null,
        detail207: null,
        detail500: null,
        large: null,
        medium: null,
        origin: null,
        small: null,
        thumbnail: null,
        xSmall: null
      },
      creators: [],
      creatorsFromDescription: [],
      dateFirstEdition: null,
      edition: null,
      fictionNonfiction: null,
      genreAndForm: [],
      hostPublication: null,
      identifiers: [],
      languages: null,
      latestPrinting: null,
      localId: null,
      manifestationParts: null,
      marc: null,
      materialTypes: [],
      notes: [],
      ownerWork: {} as any,
      physicalDescription: null,
      publisher: [],
      recordCreationDate: "2021-01-01",
      relatedPublications: [],
      relations: {
        __typename: "Relations",
        continuedIn: [],
        continues: [],
        discussedIn: [],
        discusses: [],
        hasAdaptation: [],
        hasAnalysis: [],
        hasCreatorDescription: [],
        hasDescriptionFromPublisher: [],
        hasManuscript: [],
        hasReusedReview: [],
        hasReview: [],
        hasSoundtrack: [],
        hasTrack: [],
        isAdaptationOf: [],
        isAnalysisOf: [],
        isDescriptionFromPublisherOf: [],
        isManuscriptOf: [],
        isPartOfAlbum: [],
        isPartOfManifestation: [],
        isReusedReviewOf: [],
        isReviewOf: [],
        isSoundtrackOfGame: [],
        isSoundtrackOfMovie: []
      },
      review: null,
      series: [],
      sheetMusicCategories: null,
      shelfmark: null,
      source: [],
      subjects: {
        __typename: "SubjectContainer",
        all: [],
        dbcVerified: []
      },
      tableOfContents: null,
      titles: {
        __typename: "ManifestationTitles",
        alternative: [],
        full: [],
        identifyingAddition: null,
        main: [],
        original: null,
        parallel: [],
        sort: "",
        standard: null,
        titlePlusLanguage: null,
        translated: null,
        tvSeries: null
      },
      traceId: "traceId",
      unit: null,
      universes: [],
      volume: null,
      workTypes: [],
      workYear: null
    },
    mostRelevant: [],
    searchHits: null
  },
  marc: null,
  materialTypes: [
    {
      __typename: "MaterialType",
      materialTypeGeneral: {
        __typename: "GeneralMaterialType",
        code: GeneralMaterialTypeCodeEnum.Books,
        display: "bøger"
      },
      materialTypeSpecific: {
        __typename: "SpecificMaterialType",
        code: "BOOK_FICTION",
        display: "bog"
      }
    }
  ],
  relations: {
    __typename: "Relations",
    hasReview: [],
    hasAdaptation: [],
    continuedIn: [],
    continues: [],
    discussedIn: [],
    discusses: [],
    hasAnalysis: [],
    hasCreatorDescription: [],
    hasDescriptionFromPublisher: [],
    hasManuscript: [],
    hasReusedReview: [],
    hasSoundtrack: [],
    hasTrack: [],
    isAdaptationOf: [],
    isAnalysisOf: [],
    isDescriptionFromPublisherOf: [],
    isManuscriptOf: [],
    isPartOfAlbum: [],
    isPartOfManifestation: [],
    isReusedReviewOf: [],
    isReviewOf: [],
    isSoundtrackOfGame: [],
    isSoundtrackOfMovie: []
  },
  series: [],
  subjects: {
    __typename: "SubjectContainer",
    all: [],
    dbcVerified: []
  },
  titles: {
    __typename: "WorkTitles",
    full: ["De syv søstre : Maias historie"],
    main: ["De syv søstre"],
    original: ["The seven sisters"],
    parallel: [],
    sort: "De syv søstre",
    standard: null,
    titlePlusLanguage: null,
    translated: null,
    tvSeries: null
  },
  traceId: "traceId",
  universes: [],
  workTypes: [WorkTypeEnum.Literature],
  workYear: {
    __typename: "PublicationYear",
    year: 2016,
    display: "2016"
  }
}));
