/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The image to be shown for the campaign
 */
export type CampaignMatchPOST200DataImage = {
  /** The url to the image */
  url?: string;
  /** The alt text for the image */
  alt?: string;
};
