/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type CampaignMatchPOSTBodyItemValuesItem = {
  key?: string;
  score?: number;
  term?: string;
};
