/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { CampaignMatchPOST200Data } from "./campaignMatchPOST200Data";

export type CampaignMatchPOST200 = {
  /** The matching campaign */
  data?: CampaignMatchPOST200Data;
};
