/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplDasDigitalArticleOrderPOSTFormat =
  typeof DplDasDigitalArticleOrderPOSTFormat[keyof typeof DplDasDigitalArticleOrderPOSTFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DplDasDigitalArticleOrderPOSTFormat = {
  json: "json"
} as const;
