/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursPOSTFormat =
  typeof DplOpeningHoursPOSTFormat[keyof typeof DplOpeningHoursPOSTFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DplOpeningHoursPOSTFormat = {
  json: "json"
} as const;
