/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { DplOpeningHoursListGETFormat } from "./dplOpeningHoursListGETFormat";

export type DplOpeningHoursListGETParams = {
  _format?: DplOpeningHoursListGETFormat;
  branch_id?: number;
  from_date?: string;
  to_date?: string;
};
