/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { DplOpeningHoursGETFormat } from "./dplOpeningHoursGETFormat";

export type DplOpeningHoursGETParams = { _format?: DplOpeningHoursGETFormat };
