/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursLegacyListGET200Item = {
  /** The (t)id of the opening hours category. */
  category_tid: number;
  /** The date which the opening hours applies to. In ISO 8601 format. */
  date: string;
  /** When the opening hours end. In format HH:MM */
  end_time: string;
  /** The node Id of the branch the opening hours instance belongs to. */
  nid: number;
  /**
   * Additional notice regarding the opening hours.
   * @nullable
   */
  notice: string | null;
  /** When the opening hours start. In format HH:MM */
  start_time: string;
};
