/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { DplOpeningHoursDeleteDELETE_Format } from "./dplOpeningHoursDeleteDELETEFormat";

export type DplOpeningHoursDeleteDELETEParams = {
  /**
   * Request format
   */
  _format?: DplOpeningHoursDeleteDELETE_Format;
  /**
   * The id of the repetition to delete. <br/>If this is provided then all opening hours from the provided instance to the final instance in the provided repetition will be deleted.
   */
  repetition_id?: number;
};
