/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { DplOpeningHoursUpdatePATCH_Format } from "./dplOpeningHoursUpdatePATCHFormat";

export type DplOpeningHoursUpdatePATCHParams = {
  /**
   * Request format
   */
  _format?: DplOpeningHoursUpdatePATCH_Format;
};
