/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export type DplOpeningHoursCreatePOST200Category = {
  /** A CSS compatible color code which can be used to represent the category */
  color: string;
  title: string;
};
