/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * Where the event occurs.
 */
export type EventsGET200ItemAddress = {
  /** Name of the location where the event occurs. This could be the name of a library branch. */
  location?: string;
  /** Street name and number. */
  street: string;
  /** Zip code. */
  zip_code: number;
  /** City. */
  city: string;
  /** Country code in ISO 3166-1 alpha-2 format. E.g. DK for Denmark. */
  country: string;
};
