/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The main image for the event.
 */
export type EventsGET200ItemImage = {
  /** An absolute url for the image. This is a link to the original, unaltered file, so the size, aspect ratio, and file format will be different from event to event. */
  url: string;
};
