/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * When the event occurs.
 */
export type EventsGET200ItemDateTime = {
  /** End time in ISO 8601 format. */
  end: string;
  /** Start time in ISO 8601 format. */
  start: string;
};
