/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventsGET200ItemImage } from "./eventsGET200ItemImage";
import type { EventsGET200ItemState } from "./eventsGET200ItemState";
import type { EventsGET200ItemDateTime } from "./eventsGET200ItemDateTime";
import type { EventsGET200ItemAddress } from "./eventsGET200ItemAddress";
import type { EventsGET200ItemTicketCategoriesItem } from "./eventsGET200ItemTicketCategoriesItem";
import type { EventsGET200ItemSeries } from "./eventsGET200ItemSeries";
import type { EventsGET200ItemExternalData } from "./eventsGET200ItemExternalData";

export type EventsGET200Item = {
  /** A unique identifer for the event. */
  uuid: string;
  /** The event title. */
  title: string;
  /** An absolute url end users should use to view the event at the website. */
  url: string;
  /** When the event was created. In ISO 8601 format. */
  created_at: string;
  /** When the event was last updated. In ISO 8601 format. */
  updated_at: string;
  /** The main image for the event. */
  image?: EventsGET200ItemImage;
  /** The state of the event. */
  state: EventsGET200ItemState;
  /** When the event occurs. */
  date_time: EventsGET200ItemDateTime;
  /** Where the event occurs. */
  address?: EventsGET200ItemAddress;
  /** Ticket categories used for the event. Not present for events without ticketing. */
  ticket_categories?: EventsGET200ItemTicketCategoriesItem[];
  /** An event may be part of a series. One example of this is recurring events. */
  series?: EventsGET200ItemSeries;
  /** An editorial description of the event. */
  description?: string;
  /** Data for the event provided by a third party. */
  external_data?: EventsGET200ItemExternalData;
};
