/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * Number of tickets for the event.
 */
export type EventsGET200ItemTicketCategoriesItemCount = {
  /** Total number of tickets for the event. */
  total?: number;
};
