/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * An event may be part of a series. One example of this is recurring events.
 */
export type EventsGET200ItemSeries = {
  /** The unique identifier for the series. All events belonging to the same series will have the same value. */
  uuid: string;
};
