/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventPATCH_Format } from "./eventPATCHFormat";

export type EventPATCHParams = {
  /**
   * Request format
   */
  _format?: EventPATCH_Format;
};
