/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventsGET_Format } from "./eventsGETFormat";

export type EventsGETParams = {
  /**
   * Request format
   */
  _format?: EventsGET_Format;
  /**
   * Retrieve events which occur after and including the provided date. In ISO 8601 format.
   */
  from_date?: string;
};
