/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The main image for the event.
 */
export type EventsGET200ItemImage = {
  /** An absolute url for the image. */
  url: string;
};
