/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

/**
 * The state of the event.
 */
export type EventsGET200ItemState =
  (typeof EventsGET200ItemState)[keyof typeof EventsGET200ItemState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventsGET200ItemState = {
  TicketSaleNotOpen: "TicketSaleNotOpen",
  Active: "Active",
  SoldOut: "SoldOut",
  Cancelled: "Cancelled",
  Occurred: "Occurred"
} as const;
