/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { EventsGET_Format } from "./eventsGETFormat";

export type EventsGETParams = {
  /**
   * Request format
   */
  _format?: EventsGET_Format;
};
