/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export * from "./campaignMatchPOST200";
export * from "./campaignMatchPOST200Data";
export * from "./campaignMatchPOST200DataImage";
export * from "./campaignMatchPOSTBodyItem";
export * from "./campaignMatchPOSTBodyItemValuesItem";
export * from "./campaignMatchPOSTFormat";
export * from "./campaignMatchPOSTParams";
export * from "./dplOpeningHoursCreatePOST200Item";
export * from "./dplOpeningHoursCreatePOST200ItemCategory";
export * from "./dplOpeningHoursCreatePOST200ItemRepetition";
export * from "./dplOpeningHoursCreatePOST200ItemRepetitionType";
export * from "./dplOpeningHoursCreatePOST200ItemRepetitionWeeklyData";
export * from "./dplOpeningHoursCreatePOSTFormat";
export * from "./dplOpeningHoursCreatePOSTOpeningHoursInstanceBody";
export * from "./dplOpeningHoursCreatePOSTOpeningHoursInstanceBodyCategory";
export * from "./dplOpeningHoursCreatePOSTOpeningHoursInstanceBodyRepetition";
export * from "./dplOpeningHoursCreatePOSTOpeningHoursInstanceBodyRepetitionType";
export * from "./dplOpeningHoursCreatePOSTOpeningHoursInstanceBodyRepetitionWeeklyData";
export * from "./dplOpeningHoursCreatePOSTParams";
export * from "./dplOpeningHoursDeleteDELETEFormat";
export * from "./dplOpeningHoursDeleteDELETEParams";
export * from "./dplOpeningHoursListGET200Item";
export * from "./dplOpeningHoursListGET200ItemCategory";
export * from "./dplOpeningHoursListGET200ItemRepetition";
export * from "./dplOpeningHoursListGET200ItemRepetitionType";
export * from "./dplOpeningHoursListGET200ItemRepetitionWeeklyData";
export * from "./dplOpeningHoursListGETFormat";
export * from "./dplOpeningHoursListGETParams";
export * from "./dplOpeningHoursUpdatePATCH200Item";
export * from "./dplOpeningHoursUpdatePATCH200ItemCategory";
export * from "./dplOpeningHoursUpdatePATCH200ItemRepetition";
export * from "./dplOpeningHoursUpdatePATCH200ItemRepetitionType";
export * from "./dplOpeningHoursUpdatePATCH200ItemRepetitionWeeklyData";
export * from "./dplOpeningHoursUpdatePATCHFormat";
export * from "./dplOpeningHoursUpdatePATCHParams";
export * from "./eventPATCHBody";
export * from "./eventPATCHBodyExternalData";
export * from "./eventPATCHBodyState";
export * from "./eventPATCHFormat";
export * from "./eventPATCHParams";
export * from "./eventsGET200Item";
export * from "./eventsGET200ItemAddress";
export * from "./eventsGET200ItemDateTime";
export * from "./eventsGET200ItemExternalData";
export * from "./eventsGET200ItemImage";
export * from "./eventsGET200ItemSeries";
export * from "./eventsGET200ItemState";
export * from "./eventsGET200ItemTicketCategoriesItem";
export * from "./eventsGET200ItemTicketCategoriesItemPrice";
export * from "./eventsGETFormat";
export * from "./eventsGETParams";
export * from "./proxyUrlGET200";
export * from "./proxyUrlGET200Data";
export * from "./proxyUrlGETFormat";
export * from "./proxyUrlGETParams";
export * from "./dplOpeningHoursLegacyListGET200Item";
export * from "./dplOpeningHoursLegacyListGETFormat";
export * from "./dplOpeningHoursLegacyListGETParams";
