/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export * from "./campaignMatchPOST200";
export * from "./campaignMatchPOST200Data";
export * from "./campaignMatchPOST200DataImage";
export * from "./campaignMatchPOSTBodyItem";
export * from "./campaignMatchPOSTBodyItemValuesItem";
export * from "./campaignMatchPOSTFormat";
export * from "./campaignMatchPOSTParams";
export * from "./dplOpeningHoursCreatePOST200";
export * from "./dplOpeningHoursCreatePOST200Category";
export * from "./dplOpeningHoursCreatePOSTBody";
export * from "./dplOpeningHoursCreatePOSTBodyCategory";
export * from "./dplOpeningHoursCreatePOSTFormat";
export * from "./dplOpeningHoursCreatePOSTParams";
export * from "./dplOpeningHoursDeleteDELETEFormat";
export * from "./dplOpeningHoursDeleteDELETEParams";
export * from "./dplOpeningHoursListGET200Item";
export * from "./dplOpeningHoursListGET200ItemCategory";
export * from "./dplOpeningHoursListGETFormat";
export * from "./dplOpeningHoursListGETParams";
export * from "./dplOpeningHoursUpdatePATCH200";
export * from "./dplOpeningHoursUpdatePATCH200Category";
export * from "./dplOpeningHoursUpdatePATCHBody";
export * from "./dplOpeningHoursUpdatePATCHBodyCategory";
export * from "./dplOpeningHoursUpdatePATCHFormat";
export * from "./dplOpeningHoursUpdatePATCHParams";
export * from "./eventPATCHBody";
export * from "./eventPATCHBodyExternalData";
export * from "./eventPATCHBodyState";
export * from "./eventPATCHFormat";
export * from "./eventPATCHParams";
export * from "./eventsGET200Item";
export * from "./eventsGET200ItemAddress";
export * from "./eventsGET200ItemDateTime";
export * from "./eventsGET200ItemExternalData";
export * from "./eventsGET200ItemImage";
export * from "./eventsGET200ItemSeries";
export * from "./eventsGET200ItemState";
export * from "./eventsGET200ItemTicketCategoriesItem";
export * from "./eventsGET200ItemTicketCategoriesItemCount";
export * from "./eventsGET200ItemTicketCategoriesItemPrice";
export * from "./eventsGETFormat";
export * from "./eventsGETParams";
export * from "./proxyUrlGET200";
export * from "./proxyUrlGET200Data";
export * from "./proxyUrlGETFormat";
export * from "./proxyUrlGETParams";
