/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */

export * from "./campaignMatchPOST200";
export * from "./campaignMatchPOST200Data";
export * from "./campaignMatchPOST200DataImage";
export * from "./campaignMatchPOSTBodyItem";
export * from "./campaignMatchPOSTBodyItemValuesItem";
export * from "./campaignMatchPOSTFormat";
export * from "./campaignMatchPOSTParams";
export * from "./dplDasDigitalArticleOrderPOSTBody";
export * from "./dplDasDigitalArticleOrderPOSTFormat";
export * from "./dplDasDigitalArticleOrderPOSTParams";
export * from "./proxyUrlGET200";
export * from "./proxyUrlGET200Data";
export * from "./proxyUrlGETFormat";
export * from "./proxyUrlGETParams";
