/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { ProxyUrlGET_Format } from "./proxyUrlGETFormat";

export type ProxyUrlGETParams = {
  /**
   * Request format
   */
  _format?: ProxyUrlGET_Format;
  /**
   * A url to an online resource which may be accessible through a proxy which requires rewriting of the url
   */
  url: string;
};
