/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * DPL CMS - REST API
 * The REST API provide by the core REST module.
 * OpenAPI spec version: Versioning not supported
 */
import type { ProxyUrlGETFormat } from "./proxyUrlGETFormat";

export type ProxyUrlGETParams = { _format?: ProxyUrlGETFormat; url: string };
