import { ComplexSearchFacetsEnum } from "../../../core/dbc-gateway/generated/graphql";
import type { Option } from "./suggestions";

/**
 * Static options configuration for AdvancedSearchSelect.
 * These options are fixed and do not depend on search results.
 * Only configured facets have options defined.
 *
 * Values are based on production data and follow Danish library conventions.
 */
export const ADVANCED_SEARCH_SELECT_OPTIONS: Partial<
  Record<ComplexSearchFacetsEnum, Option[]>
> = {
  [ComplexSearchFacetsEnum.Genreandform]: [
    { label: "romaner", value: "romaner" },
    { label: "noveller", value: "noveller" },
    { label: "digte", value: "digte" },
    { label: "biografier", value: "biografier" },
    { label: "tv-serier", value: "tv-serier" },
    { label: "dokumentarfilm", value: "dokumentarfilm" },
    { label: "børnefilm", value: "børnefilm" },
    { label: "drama", value: "drama" },
    { label: "actionfilm", value: "actionfilm" },
    { label: "rock", value: "rock" },
    { label: "jazz", value: "jazz" },
    { label: "pop", value: "pop" },
    { label: "shooters", value: "shooters" },
    { label: "actionspil", value: "actionspil" },
    { label: "adventurespil", value: "adventurespil" },
    { label: "60'er rock", value: "60'er rock" },
    { label: "70'er rock", value: "70'er rock" },
    { label: "ambient", value: "ambient" },
    { label: "americana", value: "americana" },
    { label: "analyser", value: "analyser" },
    { label: "animationsfilm", value: "animationsfilm" },
    {
      label: "animationsfilm mest for børn",
      value: "animationsfilm mest for børn"
    },
    { label: "anmeldelser", value: "anmeldelser" },
    { label: "arabisk musik", value: "arabisk musik" },
    { label: "arier", value: "arier" },
    { label: "barndomserindringer", value: "barndomserindringer" },
    { label: "barok", value: "barok" },
    { label: "betænkninger", value: "betænkninger" },
    { label: "bibliografier", value: "bibliografier" },
    { label: "billedbøger", value: "billedbøger" },
    { label: "billedværker", value: "billedværker" },
    { label: "biografiske film", value: "biografiske film" },
    { label: "biografiske romaner", value: "biografiske romaner" },
    { label: "bluegrass", value: "bluegrass" },
    { label: "blues", value: "blues" },
    { label: "bop", value: "bop" },
    { label: "breve", value: "breve" },
    { label: "børnemusik", value: "børnemusik" },
    { label: "børnesange", value: "børnesange" },
    { label: "causerier", value: "causerier" },
    { label: "chicago blues", value: "chicago blues" },
    { label: "country", value: "country" },
    { label: "crossover", value: "crossover" },
    { label: "dagbøger", value: "dagbøger" },
    { label: "dance", value: "dance" },
    { label: "dansk skønlitteratur", value: "dansk skønlitteratur" },
    { label: "death metal", value: "death metal" },
    { label: "digt(e)", value: "digt(e)" },
    { label: "disputatser", value: "disputatser" },
    { label: "dramatik", value: "dramatik" },
    { label: "dyrefortællinger", value: "dyrefortællinger" },
    {
      label: "eksamensopgaver under disputatsniveau",
      value: "eksamensopgaver under disputatsniveau"
    },
    { label: "electronica", value: "electronica" },
    { label: "encyklopædier", value: "encyklopædier" },
    { label: "erindringer", value: "erindringer" },
    { label: "essay(s)", value: "essay(s)" },
    { label: "essays", value: "essays" },
    { label: "eventyr", value: "eventyr" },
    { label: "eventyrlige fortællinger", value: "eventyrlige fortællinger" },
    { label: "evergreen", value: "evergreen" },
    { label: "fantastiske fortællinger", value: "fantastiske fortællinger" },
    { label: "fantasy", value: "fantasy" },
    { label: "filmmusik", value: "filmmusik" },
    { label: "filmmusik - soundtracks", value: "filmmusik - soundtracks" },
    { label: "folk", value: "folk" },
    { label: "folkemusik", value: "folkemusik" },
    { label: "for børn", value: "for børn" },
    { label: "forfatterportræt", value: "forfatterportræt" },
    { label: "fortællinger", value: "fortællinger" },
    { label: "fotografier", value: "fotografier" },
    { label: "funk", value: "funk" },
    { label: "fusion", value: "fusion" },
    { label: "garage", value: "garage" },
    { label: "gospel", value: "gospel" },
    { label: "gys", value: "gys" },
    { label: "gå på opdagelse", value: "gå på opdagelse" },
    { label: "gør-det-selv", value: "gør-det-selv" },
    { label: "heavy metal", value: "heavy metal" },
    { label: "heavy rock", value: "heavy rock" },
    { label: "hip hop", value: "hip hop" },
    { label: "historiske romaner", value: "historiske romaner" },
    { label: "horror", value: "horror" },
    { label: "house", value: "house" },
    { label: "humor", value: "humor" },
    { label: "håndbøger", value: "håndbøger" },
    { label: "hækleopskrifter", value: "hækleopskrifter" },
    { label: "idebøger", value: "idebøger" },
    { label: "idematerialer", value: "idematerialer" },
    { label: "instrumentskoler", value: "instrumentskoler" },
    { label: "interviews", value: "interviews" },
    { label: "jazz-dansk", value: "jazz-dansk" },
    { label: "jubilæumsskrifter", value: "jubilæumsskrifter" },
    { label: "julemusik", value: "julemusik" },
    { label: "julesange", value: "julesange" },
    { label: "kammermusik", value: "kammermusik" },
    { label: "kantate", value: "kantate" },
    { label: "kataloger", value: "kataloger" },
    {
      label: "kataloger (beholdningsbibliografi)",
      value: "kataloger (beholdningsbibliografi)"
    },
    { label: "keltisk musik", value: "keltisk musik" },
    { label: "kirkemusik", value: "kirkemusik" },
    { label: "klassik", value: "klassik" },
    { label: "klassisk musik", value: "klassisk musik" },
    { label: "klassisk musik 1950 ->", value: "klassisk musik 1950 ->" },
    { label: "klassiske symfonier", value: "klassiske symfonier" },
    { label: "klaver solo", value: "klaver solo" },
    { label: "kogebøger", value: "kogebøger" },
    { label: "komedier", value: "komedier" },
    { label: "kor", value: "kor" },
    { label: "krimi", value: "krimi" },
    { label: "kronikker", value: "kronikker" },
    { label: "kærlighed", value: "kærlighed" },
    { label: "kærlighedsromaner", value: "kærlighedsromaner" },
    { label: "landliv", value: "landliv" },
    { label: "latin", value: "latin" },
    { label: "leksika", value: "leksika" },
    { label: "litteraturanalyser", value: "litteraturanalyser" },
    { label: "love", value: "love" },
    { label: "lydret", value: "lydret" },
    { label: "lærebøger", value: "lærebøger" },
    { label: "lærervejledninger", value: "lærervejledninger" },
    { label: "manga", value: "manga" },
    { label: "messe", value: "messe" },
    { label: "minimalisme", value: "minimalisme" },
    { label: "music minus one", value: "music minus one" },
    { label: "mønstre", value: "mønstre" },
    { label: "nationalromantik", value: "nationalromantik" },
    { label: "nekrologer", value: "nekrologer" },
    { label: "neoklassik", value: "neoklassik" },
    { label: "new wave", value: "new wave" },
    { label: "novelle(r)", value: "novelle(r)" },
    { label: "opera", value: "opera" },
    { label: "operaarier", value: "operaarier" },
    { label: "opgaver", value: "opgaver" },
    { label: "opskrifter", value: "opskrifter" },
    { label: "ordbøger", value: "ordbøger" },
    { label: "partiturer", value: "partiturer" },
    { label: "pegebøger", value: "pegebøger" },
    { label: "pjecer", value: "pjecer" },
    { label: "podcasts", value: "podcasts" },
    { label: "politifilm", value: "politifilm" },
    { label: "politiromaner", value: "politiromaner" },
    { label: "progressiv rock", value: "progressiv rock" },
    { label: "prædikener", value: "prædikener" },
    { label: "psykedelisk rock", value: "psykedelisk rock" },
    { label: "psykologisk thriller", value: "psykologisk thriller" },
    { label: "punk", value: "punk" },
    { label: "r&b", value: "r&b" },
    { label: "reggae", value: "reggae" },
    { label: "rejsebeskrivelser", value: "rejsebeskrivelser" },
    { label: "rejseguides", value: "rejseguides" },
    { label: "renæssance", value: "renæssance" },
    { label: "rhythm & blues", value: "rhythm & blues" },
    { label: "rim", value: "rim" },
    { label: "rockfilm", value: "rockfilm" },
    { label: "romantik", value: "romantik" },
    { label: "rytmisk musik", value: "rytmisk musik" },
    { label: "sagn", value: "sagn" },
    { label: "salme", value: "salme" },
    { label: "samfundskritik", value: "samfundskritik" },
    { label: "samfundsskildringer", value: "samfundsskildringer" },
    { label: "sangbøger", value: "sangbøger" },
    { label: "sange", value: "sange" },
    { label: "satire", value: "satire" },
    { label: "science fiction", value: "science fiction" },
    { label: "senromantik", value: "senromantik" },
    { label: "serier", value: "serier" },
    { label: "singer/songwriter", value: "singer/songwriter" },
    { label: "sjove bøger", value: "sjove bøger" },
    { label: "skuespil", value: "skuespil" },
    { label: "slægtsromaner", value: "slægtsromaner" },
    { label: "solosang", value: "solosang" },
    { label: "soul", value: "soul" },
    { label: "spænding", value: "spænding" },
    { label: "statistikker", value: "statistikker" },
    { label: "strikkemønstre", value: "strikkemønstre" },
    { label: "strikkeopskrifter", value: "strikkeopskrifter" },
    { label: "studiepartiturer", value: "studiepartiturer" },
    { label: "swing", value: "swing" },
    { label: "sygehistorier", value: "sygehistorier" },
    { label: "symfoni", value: "symfoni" },
    { label: "synthpop", value: "synthpop" },
    { label: "tabelværker", value: "tabelværker" },
    { label: "techno", value: "techno" },
    { label: "tegnefilm", value: "tegnefilm" },
    { label: "tegneserier", value: "tegneserier" },
    {
      label: "teknisk-videnskabelig rapporter",
      value: "teknisk-videnskabelig rapporter"
    },
    { label: "tests", value: "tests" },
    { label: "thriller", value: "thriller" },
    { label: "tidsskrifter", value: "tidsskrifter" },
    { label: "udstillingskataloger", value: "udstillingskataloger" },
    { label: "undersøgelser", value: "undersøgelser" },
    { label: "undervisningsmaterialer", value: "undervisningsmaterialer" },
    { label: "vejledninger", value: "vejledninger" },
    {
      label: "vejvisere, medlemsfortegnelser o.l.",
      value: "vejvisere, medlemsfortegnelser o.l."
    },
    { label: "verdensmusik", value: "verdensmusik" },
    { label: "vise", value: "vise" },
    { label: "viser", value: "viser" },
    { label: "wienerklassik", value: "wienerklassik" },
    { label: "young adult", value: "young adult" },
    { label: "årbøger", value: "årbøger" },
    { label: "årspublikationer", value: "årspublikationer" },
    { label: "øvelser", value: "øvelser" }
  ],
  [ComplexSearchFacetsEnum.Mainlanguage]: [
    { label: "dansk", value: "dansk" },
    { label: "engelsk", value: "engelsk" },
    { label: "tysk", value: "tysk" },
    { label: "fransk", value: "fransk" },
    { label: "spansk", value: "spansk" },
    { label: "svensk", value: "svensk" },
    { label: "norsk", value: "norsk" },
    { label: "italiensk", value: "italiensk" },
    { label: "arabisk", value: "arabisk" },
    { label: "finsk", value: "finsk" },
    { label: "nederlandsk", value: "nederlandsk" },
    { label: "polsk", value: "polsk" },
    { label: "russisk", value: "russisk" },
    { label: "tyrkisk", value: "tyrkisk" }
  ],
  [ComplexSearchFacetsEnum.Publicationyear]: [
    { label: "2025", value: "2025" },
    { label: "2024", value: "2024" },
    { label: "2023", value: "2023" },
    { label: "2022", value: "2022" },
    { label: "2021", value: "2021" },
    { label: "2020", value: "2020" },
    { label: "2019", value: "2019" },
    { label: "2018", value: "2018" },
    { label: "2017", value: "2017" },
    { label: "2016", value: "2016" },
    { label: "2015", value: "2015" },
    { label: "2014", value: "2014" },
    { label: "2013", value: "2013" },
    { label: "2012", value: "2012" },
    { label: "2011", value: "2011" },
    { label: "2010", value: "2010" }
  ],
  [ComplexSearchFacetsEnum.Ages]: [
    { label: "for 0 år", value: "for 0 år" },
    { label: "for 1 år", value: "for 1 år" },
    { label: "for 2 år", value: "for 2 år" },
    { label: "for 3 år", value: "for 3 år" },
    { label: "for 4 år", value: "for 4 år" },
    { label: "for 5 år", value: "for 5 år" },
    { label: "for 6 år", value: "for 6 år" },
    { label: "for 7 år", value: "for 7 år" },
    { label: "for 8 år", value: "for 8 år" },
    { label: "for 9 år", value: "for 9 år" },
    { label: "for 10 år", value: "for 10 år" },
    { label: "for 11 år", value: "for 11 år" },
    { label: "for 12 år", value: "for 12 år" },
    { label: "for 13 år", value: "for 13 år" },
    { label: "for 14 år", value: "for 14 år" },
    { label: "for 15 år", value: "for 15 år" },
    { label: "for 16 år", value: "for 16 år" },
    { label: "for 17 år", value: "for 17 år" },
    { label: "for 18 år", value: "for 18 år" }
  ],
  [ComplexSearchFacetsEnum.Source]: [
    {
      label: "Besættelsestidsbibliografien",
      value: "Besættelsestidsbibliografien"
    },
    { label: "Sportline", value: "Sportline" },
    {
      label: "Bibliografi over Dansk Kunst",
      value: "Bibliografi over Dansk Kunst"
    },
    {
      label: "Dansk Historisk Bibliografi",
      value: "Dansk Historisk Bibliografi"
    },
    { label: "Dania Polyglotta", value: "Dania Polyglotta" },
    {
      label: "Dansk Musiklitterær Bibliografi",
      value: "Dansk Musiklitterær Bibliografi"
    },
    {
      label: "Dansk Litteraturhistorisk Bibliografi",
      value: "Dansk Litteraturhistorisk Bibliografi"
    },
    {
      label: "Kongelige Teater programartikler",
      value: "Kongelige Teater programartikler"
    }
  ]
};
