import type { Option, RangePreset } from "../types";

const currentYear = new Date().getFullYear();

export const MATERIAL_TYPE_OPTIONS: Option[] = [
  { label: "Bøger", value: "bøger" },
  { label: "E-bøger", value: "e-bøger" },
  { label: "Lydbøger", value: "lydbøger" },
  { label: "Podcasts", value: "podcasts" },
  { label: "Film", value: "film" },
  { label: "Tv-serier", value: "tv-serier" },
  { label: "Musik", value: "musik" },
  { label: "Noder", value: "noder" },
  { label: "Aviser og tidsskrifter", value: "aviser og tidsskrifter" },
  { label: "Tegneserier", value: "tegneserier" },
  { label: "Computerspil", value: "computerspil" },
  { label: "Artikler", value: "artikler" },
  { label: "Brætspil", value: "brætspil" },
  { label: "Billedmaterialer", value: "billedmaterialer" },
  { label: "Øvrige", value: "øvrige" }
];

export const GENRE_OPTIONS: Option[] = [
  { label: "romaner", value: "romaner" },
  { label: "noveller", value: "noveller" },
  { label: "digte", value: "digte" },
  { label: "biografier", value: "biografier" },
  { label: "tv-serier", value: "tv-serier" },
  { label: "dokumentarfilm", value: "dokumentarfilm" },
  { label: "børnefilm", value: "børnefilm" },
  { label: "drama", value: "drama" },
  { label: "actionfilm", value: "actionfilm" },
  { label: "rock", value: "rock" },
  { label: "jazz", value: "jazz" },
  { label: "pop", value: "pop" },
  { label: "shooters", value: "shooters" },
  { label: "actionspil", value: "actionspil" },
  { label: "adventurespil", value: "adventurespil" },
  { label: "60'er rock", value: "60'er rock" },
  { label: "70'er rock", value: "70'er rock" },
  { label: "ambient", value: "ambient" },
  { label: "americana", value: "americana" },
  { label: "analyser", value: "analyser" },
  { label: "animationsfilm", value: "animationsfilm" },
  {
    label: "animationsfilm mest for børn",
    value: "animationsfilm mest for børn"
  },
  { label: "anmeldelser", value: "anmeldelser" },
  { label: "arabisk musik", value: "arabisk musik" },
  { label: "arier", value: "arier" },
  { label: "barndomserindringer", value: "barndomserindringer" },
  { label: "barok", value: "barok" },
  { label: "betænkninger", value: "betænkninger" },
  { label: "bibliografier", value: "bibliografier" },
  { label: "billedbøger", value: "billedbøger" },
  { label: "billedværker", value: "billedværker" },
  { label: "biografiske film", value: "biografiske film" },
  { label: "biografiske romaner", value: "biografiske romaner" },
  { label: "bluegrass", value: "bluegrass" },
  { label: "blues", value: "blues" },
  { label: "bop", value: "bop" },
  { label: "breve", value: "breve" },
  { label: "børnemusik", value: "børnemusik" },
  { label: "børnesange", value: "børnesange" },
  { label: "causerier", value: "causerier" },
  { label: "chicago blues", value: "chicago blues" },
  { label: "country", value: "country" },
  { label: "crossover", value: "crossover" },
  { label: "dagbøger", value: "dagbøger" },
  { label: "dance", value: "dance" },
  { label: "dansk skønlitteratur", value: "dansk skønlitteratur" },
  { label: "death metal", value: "death metal" },
  { label: "digt(e)", value: "digt(e)" },
  { label: "disputatser", value: "disputatser" },
  { label: "dramatik", value: "dramatik" },
  { label: "dyrefortællinger", value: "dyrefortællinger" },
  {
    label: "eksamensopgaver under disputatsniveau",
    value: "eksamensopgaver under disputatsniveau"
  },
  { label: "electronica", value: "electronica" },
  { label: "encyklopædier", value: "encyklopædier" },
  { label: "erindringer", value: "erindringer" },
  { label: "essay(s)", value: "essay(s)" },
  { label: "essays", value: "essays" },
  { label: "eventyr", value: "eventyr" },
  { label: "eventyrlige fortællinger", value: "eventyrlige fortællinger" },
  { label: "evergreen", value: "evergreen" },
  { label: "fantastiske fortællinger", value: "fantastiske fortællinger" },
  { label: "fantasy", value: "fantasy" },
  { label: "filmmusik", value: "filmmusik" },
  { label: "filmmusik - soundtracks", value: "filmmusik - soundtracks" },
  { label: "folk", value: "folk" },
  { label: "folkemusik", value: "folkemusik" },
  { label: "for børn", value: "for børn" },
  { label: "forfatterportræt", value: "forfatterportræt" },
  { label: "fortællinger", value: "fortællinger" },
  { label: "fotografier", value: "fotografier" },
  { label: "funk", value: "funk" },
  { label: "fusion", value: "fusion" },
  { label: "garage", value: "garage" },
  { label: "gospel", value: "gospel" },
  { label: "gys", value: "gys" },
  { label: "gå på opdagelse", value: "gå på opdagelse" },
  { label: "gør-det-selv", value: "gør-det-selv" },
  { label: "heavy metal", value: "heavy metal" },
  { label: "heavy rock", value: "heavy rock" },
  { label: "hip hop", value: "hip hop" },
  { label: "historiske romaner", value: "historiske romaner" },
  { label: "horror", value: "horror" },
  { label: "house", value: "house" },
  { label: "humor", value: "humor" },
  { label: "håndbøger", value: "håndbøger" },
  { label: "hækleopskrifter", value: "hækleopskrifter" },
  { label: "idebøger", value: "idebøger" },
  { label: "idematerialer", value: "idematerialer" },
  { label: "instrumentskoler", value: "instrumentskoler" },
  { label: "interviews", value: "interviews" },
  { label: "jazz-dansk", value: "jazz-dansk" },
  { label: "jubilæumsskrifter", value: "jubilæumsskrifter" },
  { label: "julemusik", value: "julemusik" },
  { label: "julesange", value: "julesange" },
  { label: "kammermusik", value: "kammermusik" },
  { label: "kantate", value: "kantate" },
  { label: "kataloger", value: "kataloger" },
  {
    label: "kataloger (beholdningsbibliografi)",
    value: "kataloger (beholdningsbibliografi)"
  },
  { label: "keltisk musik", value: "keltisk musik" },
  { label: "kirkemusik", value: "kirkemusik" },
  { label: "klassik", value: "klassik" },
  { label: "klassisk musik", value: "klassisk musik" },
  { label: "klassisk musik 1950 ->", value: "klassisk musik 1950 ->" },
  { label: "klassiske symfonier", value: "klassiske symfonier" },
  { label: "klaver solo", value: "klaver solo" },
  { label: "kogebøger", value: "kogebøger" },
  { label: "komedier", value: "komedier" },
  { label: "kor", value: "kor" },
  { label: "krimi", value: "krimi" },
  { label: "kronikker", value: "kronikker" },
  { label: "kærlighed", value: "kærlighed" },
  { label: "kærlighedsromaner", value: "kærlighedsromaner" },
  { label: "landliv", value: "landliv" },
  { label: "latin", value: "latin" },
  { label: "leksika", value: "leksika" },
  { label: "litteraturanalyser", value: "litteraturanalyser" },
  { label: "love", value: "love" },
  { label: "lydret", value: "lydret" },
  { label: "lærebøger", value: "lærebøger" },
  { label: "lærervejledninger", value: "lærervejledninger" },
  { label: "manga", value: "manga" },
  { label: "messe", value: "messe" },
  { label: "minimalisme", value: "minimalisme" },
  { label: "music minus one", value: "music minus one" },
  { label: "mønstre", value: "mønstre" },
  { label: "nationalromantik", value: "nationalromantik" },
  { label: "nekrologer", value: "nekrologer" },
  { label: "neoklassik", value: "neoklassik" },
  { label: "new wave", value: "new wave" },
  { label: "novelle(r)", value: "novelle(r)" },
  { label: "opera", value: "opera" },
  { label: "operaarier", value: "operaarier" },
  { label: "opgaver", value: "opgaver" },
  { label: "opskrifter", value: "opskrifter" },
  { label: "ordbøger", value: "ordbøger" },
  { label: "partiturer", value: "partiturer" },
  { label: "pegebøger", value: "pegebøger" },
  { label: "pjecer", value: "pjecer" },
  { label: "podcasts", value: "podcasts" },
  { label: "politifilm", value: "politifilm" },
  { label: "politiromaner", value: "politiromaner" },
  { label: "progressiv rock", value: "progressiv rock" },
  { label: "prædikener", value: "prædikener" },
  { label: "psykedelisk rock", value: "psykedelisk rock" },
  { label: "psykologisk thriller", value: "psykologisk thriller" },
  { label: "punk", value: "punk" },
  { label: "r&b", value: "r&b" },
  { label: "reggae", value: "reggae" },
  { label: "rejsebeskrivelser", value: "rejsebeskrivelser" },
  { label: "rejseguides", value: "rejseguides" },
  { label: "renæssance", value: "renæssance" },
  { label: "rhythm & blues", value: "rhythm & blues" },
  { label: "rim", value: "rim" },
  { label: "rockfilm", value: "rockfilm" },
  { label: "romantik", value: "romantik" },
  { label: "rytmisk musik", value: "rytmisk musik" },
  { label: "sagn", value: "sagn" },
  { label: "salme", value: "salme" },
  { label: "samfundskritik", value: "samfundskritik" },
  { label: "samfundsskildringer", value: "samfundsskildringer" },
  { label: "sangbøger", value: "sangbøger" },
  { label: "sange", value: "sange" },
  { label: "satire", value: "satire" },
  { label: "science fiction", value: "science fiction" },
  { label: "senromantik", value: "senromantik" },
  { label: "serier", value: "serier" },
  { label: "singer/songwriter", value: "singer/songwriter" },
  { label: "sjove bøger", value: "sjove bøger" },
  { label: "skuespil", value: "skuespil" },
  { label: "slægtsromaner", value: "slægtsromaner" },
  { label: "solosang", value: "solosang" },
  { label: "soul", value: "soul" },
  { label: "spænding", value: "spænding" },
  { label: "statistikker", value: "statistikker" },
  { label: "strikkemønstre", value: "strikkemønstre" },
  { label: "strikkeopskrifter", value: "strikkeopskrifter" },
  { label: "studiepartiturer", value: "studiepartiturer" },
  { label: "swing", value: "swing" },
  { label: "sygehistorier", value: "sygehistorier" },
  { label: "symfoni", value: "symfoni" },
  { label: "synthpop", value: "synthpop" },
  { label: "tabelværker", value: "tabelværker" },
  { label: "techno", value: "techno" },
  { label: "tegnefilm", value: "tegnefilm" },
  { label: "tegneserier", value: "tegneserier" },
  {
    label: "teknisk-videnskabelig rapporter",
    value: "teknisk-videnskabelig rapporter"
  },
  { label: "tests", value: "tests" },
  { label: "thriller", value: "thriller" },
  { label: "tidsskrifter", value: "tidsskrifter" },
  { label: "udstillingskataloger", value: "udstillingskataloger" },
  { label: "undersøgelser", value: "undersøgelser" },
  { label: "undervisningsmaterialer", value: "undervisningsmaterialer" },
  { label: "vejledninger", value: "vejledninger" },
  {
    label: "vejvisere, medlemsfortegnelser o.l.",
    value: "vejvisere, medlemsfortegnelser o.l."
  },
  { label: "verdensmusik", value: "verdensmusik" },
  { label: "vise", value: "vise" },
  { label: "viser", value: "viser" },
  { label: "wienerklassik", value: "wienerklassik" },
  { label: "young adult", value: "young adult" },
  { label: "årbøger", value: "årbøger" },
  { label: "årspublikationer", value: "årspublikationer" },
  { label: "øvelser", value: "øvelser" }
];
export const LANGUAGE_OPTIONS: Option[] = [
  { label: "dansk", value: "dansk" },
  { label: "engelsk", value: "engelsk" },
  { label: "færøsk", value: "færøsk" },
  { label: "kalaallisut", value: "kalaallisut" },
  { label: "tysk", value: "tysk" },
  { label: "fransk", value: "fransk" },
  { label: "spansk", value: "spansk" },
  { label: "svensk", value: "svensk" },
  { label: "norsk", value: "norsk" },
  { label: "arabisk", value: "arabisk" },
  { label: "finsk", value: "finsk" },
  { label: "italiensk", value: "italiensk" },
  { label: "nederlandsk", value: "nederlandsk" },
  { label: "polsk", value: "polsk" },
  { label: "russisk", value: "russisk" },
  { label: "tyrkisk", value: "tyrkisk" }
];

export const SOURCE_OPTIONS: Option[] = [];

export const YEAR_PRESETS: RangePreset[] = [
  {
    id: "current-year",
    label: `I år (${currentYear})`,
    from: currentYear,
    to: currentYear
  },
  {
    id: "last-2-years",
    label: "Seneste 2 år",
    from: currentYear - 1,
    to: currentYear
  },
  {
    id: "last-3-years",
    label: "Seneste 3 år",
    from: currentYear - 2,
    to: currentYear
  },
  {
    id: "last-5-years",
    label: "Seneste 5 år",
    from: currentYear - 4,
    to: currentYear
  },
  {
    id: "last-10-years",
    label: "Seneste 10 år",
    from: currentYear - 10,
    to: currentYear
  }
];

export const AGE_PRESETS: RangePreset[] = [
  { id: "1-2", label: "For 1-2-årige", from: 1, to: 2 },
  { id: "3-6", label: "For 3-6-årige", from: 3, to: 6 },
  { id: "7-10", label: "For 7-10-årige", from: 7, to: 10 },
  { id: "11-13", label: "For 11-13-årige", from: 11, to: 13 },
  { id: "14-16", label: "For 14-16-årige", from: 14, to: 16 },
  { id: "16+", label: "For 16+", from: 16, to: null }
];
