/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AddressV2 {
  /** City */
  city: string;
  /** c/o name */
  coName: string;
  /** Country */
  country: string;
  /** Postal code */
  postalCode: string;
  /** Street and number */
  street: string;
}
