/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AddressV3 {
  /** City */
  city: string;
  /** c/o name */
  coName: string;
  /** Country */
  country: string;
  /** Dsitrict */
  district: string;
  /** Postal code */
  postalCode: string;
  /** Street and number */
  street: string;
  /** Subdistrict */
  subDistrict: string;
}
