/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AgencyDepartment {
  /** Department identifier */
  departmentId: string;
  /** Name of the department */
  title: string;
}
