/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AgencySection {
  /** Section identifier */
  sectionId: string;
  /** Name of the section */
  title: string;
}
