/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AgencySublocation {
  /** Sub-location identifier */
  sublocationId: string;
  /** Name of the sub-location */
  title: string;
}
