/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AgencyBranch {
  /** ISIL of branch (e.g. DK-761501) */
  branchId: string;
  /** Name of branch */
  title: string;
}
