/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface AvailabilityV3 {
  /** True if materials is available on-shelf at some placement, false if all materials are lent out */
  available: boolean;
  /** The FAUST number of the Bibliographic record */
  recordId: string;
  /** True if materials can be reserved */
  reservable: boolean;
  /** Total number of current active reservations of the Bibliographic record */
  reservations: number;
}
