/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface BlockStatusRequest {
  /** Reason code for block */
  blockedReason: string;
  /** The date from which the patron should be blocked.
 The dateformat is YYYY-MM-DD, so 9th of March 2023 is written 2023-03-09. */
  blockedSince: string;
}
