/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface BlockStatus {
  /** Reason code for block */
  blockedReason: string;
  blockedSince: string;
  /** Message about block */
  message: string;
}
