/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { Period } from "./period";

export interface BookingInfo {
  period: Period;
  /** The preferred number of materials */
  preferredMaterials: number;
}
