/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronSettingsV3 } from "./patronSettingsV3";

export interface CreatePatronRequestV3 {
  cprNumber: string;
  patron: PatronSettingsV3;
  pincode: string;
}
