/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { BlockStatusRequest } from "./blockStatusRequest";
import type { PatronSettingsV6 } from "./patronSettingsV6";

export interface CreatePatronRequestV7 {
  blockStatusRequest?: BlockStatusRequest;
  patron: PatronSettingsV6;
  personIdentifier: string;
  pincode: string;
}
