/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { CreateReservation } from "./createReservation";

export interface CreateReservationBatchV2 {
  /** Reservations with duplicate record id's will be removed. */
  reservations: CreateReservation[];
  /** Will be considered normal if not set */
  type?: string;
}
