/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export type DeleteReservationsParams = {
  /**
   * a list of reservation ids for reservations that are to be deleted
   */
  reservationid: number[];
};
