/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface EmailAddressV1 {
  emailAddress: string;
  receiveNotification: boolean;
}
