/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { Periodical } from "./periodical";

export interface FeeMaterial {
  /** Name of the material group that the material belongs to */
  materialGroupName: string;
  /** Identifies the exact material covered by the fee */
  materialItemNumber: string;
  periodical?: Periodical;
  /** The FAUST number of the bibliographic record */
  recordId: string;
}
