/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export type GetBranchesParams = {
  /**
   * Identifies the branchIds which are excluded from the result
   */
  exclude?: string[];
};
