/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export type GetHoldingsLogisticsV1Params = {
  /**
   * Identifies the bibliographical records - The FAUST number.
   */
  recordid: string[];
  /**
   * Identifies the branchIds which are excluded from the result
   */
  exclude?: string[];
};
