/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { AgencyBranch } from "./agencyBranch";
import type { PlacementV1 } from "./placementV1";
import type { MaterialV4 } from "./materialV4";

export interface HoldingsLogisticsV2 {
  branch: AgencyBranch;
  lmsPlacement?: PlacementV1;
  /** Logistics placement */
  logisticsPlacement?: string[];
  /** Materials that belongs to this placement */
  materials: MaterialV4[];
}
