/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { HoldingsV3 } from "./holdingsV3";

export interface HoldingsForBibliographicalRecordV3 {
  /** An array of holdings for the materials matching the bibliographical record, as distributed across branches,
 departments and locations */
  holdings: HoldingsV3[];
  /** Identifies the bibliographical record for the available materials,
 The FAUST number */
  recordId: string;
  /** True if there is any reservable materials */
  reservable: boolean;
  /** Total number of current active reservations for the bibliographical record */
  reservations: number;
}
