/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { MaterialGroup } from "./materialGroup";
import type { Periodical } from "./periodical";

export interface MaterialV3 {
  /** True if material is available on-shelf, false if lent out */
  available: boolean;
  /** Identifies the material */
  itemNumber: string;
  materialGroup: MaterialGroup;
  periodical?: Periodical;
}
