/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface MaterialGroup {
  /** Description of the material group */
  description?: string;
  /** Name of the material group */
  name: string;
}
