/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { NewsletterGroupCategoryV1 } from "./newsletterGroupCategoryV1";
import type { NewsletterTagV1 } from "./newsletterTagV1";

export interface NewsletterV1 {
  /** The newsletter preferences */
  interestCategories?: NewsletterGroupCategoryV1[];
  /** Newsletter contact list id */
  listId: string;
  /** The newslatter name */
  name: string;
  /** The newsletter preferences */
  tags?: NewsletterTagV1[];
}
