/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface NewsletterTagV1 {
  /** The preference id stored in Mailchimp */
  id: string;
  /** The preference name stored in Mailchimp */
  name: string;
}
