/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { Period } from "./period";

export interface PatronSettingsV4 {
  /** Required if patron should receive email notifications
 Existing email addresses are overwritten with this value
 If left empty existing email addresses are deleted */
  emailAddress?: string;
  /** Notification protocols that the patron want to receive notification on. SMS and EMAIL are not included. */
  notificationProtocols?: string[];
  onHold?: Period;
  /** Required if patron should receive SMS notifications
 Existing phonenumbers are overwritten with this value
 If left empty existing phonenumbers are deleted */
  phoneNumber?: string;
  /** Language in which the patron prefers the communication with the library to take place
 If left empty default library language will be used */
  preferredLanguage?: string;
  /** ISIL-number of preferred pickup branch */
  preferredPickupBranch: string;
  receiveEmail: boolean;
  receivePostalMail: boolean;
  receiveSms: boolean;
}
