/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { EmailAddressV1 } from "./emailAddressV1";
import type { Period } from "./period";
import type { PhoneNumberV1 } from "./phoneNumberV1";

export interface PatronSettingsV6 {
  /** Existing email addresses are overwritten with these values
 If left empty existing email addresses are deleted */
  emailAddresses?: EmailAddressV1[];
  guardianVisibility: boolean;
  /** A list of interests of the patron. */
  interests?: string[];
  /** Notification protocols that the patron want to receive notification on. SMS and EMAIL are not included. */
  notificationProtocols?: string[];
  onHold?: Period;
  /** Existing phonenumbers are overwritten with these values
 If left empty existing phonenumbers are deleted */
  phoneNumbers?: PhoneNumberV1[];
  /** Language in which the patron prefers the communication with the library to take place
 If left empty default library language will be used */
  preferredLanguage?: string;
  /** ISIL-number of preferred pickup branch */
  preferredPickupBranch: string;
  receivePostalMail: boolean;
}
