/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface PatronGroup {
  /** The array of child groups of this group */
  childGroups?: PatronGroup[];
  /** The description of the group */
  description: string;
  /** The number of all members in this group, including descendants */
  membersCount: number;
  /** The name of the group */
  name: string;
  /** The patron group identifier */
  patronGroupId: number;
}
