/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { Address } from "./address";
import type { Guardian } from "./guardian";

export interface PatronWithGuardianRequest {
  address?: Address;
  cprNumber: string;
  /** Must be valid if supplied */
  email?: string;
  guardian: Guardian;
  /** The full name of the patron */
  name: string;
  /** Must be valid if supplied */
  phoneNumber?: string;
  pincode: string;
  /** Must be a valid branch id (eg. DK-761501) */
  preferredPickupBranch: string;
}
