/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface Period {
  /** Open-ended if not set */
  from?: string;
  /** Open-ended if not set */
  to?: string;
}
