/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface PeriodicalReservation {
  volume?: string;
  volumeNumber?: string;
  volumeYear?: string;
}
