/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface Periodical {
  /** A representation of the periodica volume information that is suitable for display */
  displayText: string;
  volume?: string;
  volumeNumber?: string;
  volumeYear?: string;
}
