/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface PincodeChange {
  /** Identifies the libraryCard for which the pincode is to be changed.
 This can be either a physical card or the CPR number, that is used as a libraryCard */
  libraryCardNumber: string;
  /** The new pincode for the libraryCard */
  pincode: string;
}
