/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { LoanDetailsV2 } from "./loanDetailsV2";

export interface RenewedLoanV2 {
  loanDetails: LoanDetailsV2;
  /** indicates if renewal was succesful or denied - including the reason for denial. */
  renewalStatus: string[];
}
