/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PeriodicalReservation } from "./periodicalReservation";
import type { ReservationDetailsV3 } from "./reservationDetailsV3";

export interface ReservationResultV3 {
  periodical?: PeriodicalReservation;
  /** Recordid of the record to reserve */
  recordId: string;
  reservationDetails?: ReservationDetailsV3;
  /** The reservation result */
  result: string;
}
