/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PeriodicalReservation } from "./periodicalReservation";
import type { ReservationDetails } from "./reservationDetails";

export interface ReservationResult {
  periodical?: PeriodicalReservation;
  /** Recordid of the record to reserve */
  recordId: string;
  reservationDetails?: ReservationDetails;
  /** The reservation result */
  result: string;
}
