/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { ReservationResultV2 } from "./reservationResultV2";

export interface ReservationResponseV2 {
  /** Result of each reservation */
  reservationResults: ReservationResultV2[];
  /** True if all reservation were create successfully otherwise false */
  success: boolean;
}
