/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { Guardian } from "./guardian";

export interface UpdateGuardianRequest {
  /** If patronId is provided, this field will be ignored */
  cprNumber?: string;
  guardian: Guardian;
  patronId?: number;
}
