/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronSettingsV4 } from "./patronSettingsV4";
import type { PincodeChange } from "./pincodeChange";

export interface UpdatePatronRequestV4 {
  patron?: PatronSettingsV4;
  pincodeChange?: PincodeChange;
}
