/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronSettingsV3 } from "./patronSettingsV3";
import type { PincodeChange } from "./pincodeChange";

export interface UpdatePatronRequestV3 {
  patron?: PatronSettingsV3;
  pincodeChange?: PincodeChange;
}
