/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */
import type { PatronSettingsV6 } from "./patronSettingsV6";
import type { PincodeChange } from "./pincodeChange";

export interface UpdatePatronRequestV6 {
  patron?: PatronSettingsV6;
  pincodeChange?: PincodeChange;
}
