/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface UpdateReservation {
  /** The date where the patron is no longer interested in the reserved material.
 If not set, the reservation will keep the original date. */
  expiryDate?: string;
  /** ISIL-number of pickup branch.
 If not set, the reservation will keep the original pickup branch. */
  pickupBranch?: string;
  /** Identifies the reservation */
  reservationId: number;
}
