/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * FBS Adapter
 * OpenAPI spec version: 1.0
 */

export interface UpdateReservation {
  /** The date where the patron is no longer interested in the reserved material.
 If not set, a date will be calculated from the libraries default interest period */
  expiryDate?: string;
  /** ISIL-number of pickup branch.
 If not set, will default to patrons preferred pickup branch */
  pickupBranch?: string;
  /** Identifies the reservation */
  reservationId: number;
}
