/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * Publizon Library API
 * Pubhub exists in two separate environments, each with their own server, code and database. Please use the web service located at library-api.qa.pubhub.dk when developing and testing.
Orders/loans created in test environment will not be invoiced. Please request a new license key for the production environment when you're ready to go live.
 * OpenAPI spec version: 1
 */

/**
 * 101 = Success, 105 = InvalidContentIdentifier, 118 = InvalidRequestIdentity, 120 = MaxConcurrentLoansPerBorrowerExceeded, 125 = MaxAmountPerMonthExceeded, 128 = ContentNotFound, 131 = NotLoanable, 134 = CardTemporarilyBlocked, 135 = MaxLoansOnTitleReached, 136 = InsufficientCopiesException, 137 = ReservationLimitReached, 138 = GenericFault, 139 = InvalidAgreement, 140 = AlreadyReserved, 141 = InvalidEmail, 142 = InvalidPhone, 143 = CostFreeLimitReached, 147 = CountryNotFound, 148 = InvalidInstitutionId, 149 = InvalidCardFormat, 150 = InvalidCardByCulr, 151 = CardNotFound, 152 = InvalidClientId, 153 = LoanNotFound
 */
export type ApiResponseCode =
  typeof ApiResponseCode[keyof typeof ApiResponseCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiResponseCode = {
  NUMBER_101: 101,
  NUMBER_105: 105,
  NUMBER_118: 118,
  NUMBER_120: 120,
  NUMBER_125: 125,
  NUMBER_128: 128,
  NUMBER_131: 131,
  NUMBER_134: 134,
  NUMBER_135: 135,
  NUMBER_136: 136,
  NUMBER_137: 137,
  NUMBER_138: 138,
  NUMBER_139: 139,
  NUMBER_140: 140,
  NUMBER_141: 141,
  NUMBER_142: 142,
  NUMBER_143: 143,
  NUMBER_147: 147,
  NUMBER_148: 148,
  NUMBER_149: 149,
  NUMBER_150: 150,
  NUMBER_151: 151,
  NUMBER_152: 152,
  NUMBER_153: 153
} as const;
