/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Publizon Library API
 * Pubhub exists in two separate environments, each with their own server, code and database. Please use the web service located at library-api.qa.pubhub.dk when developing and testing.
Orders/loans created in test environment will not be invoiced. Please request a new license key for the production environment when you're ready to go live.
 * OpenAPI spec version: 1
 */
import type { LibraryProductContributor } from "./libraryProductContributor";
import type { LibraryProductExternalId } from "./libraryProductExternalId";
import type { LibraryProductCategory } from "./libraryProductCategory";

export interface Product {
  /** @nullable */
  contributors?: LibraryProductContributor[] | null;
  costFree?: boolean;
  /** @nullable */
  coverUri?: string | null;
  createdUtc?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  durationInSeconds?: number | null;
  externalProductId?: LibraryProductExternalId;
  fileSizeInBytes?: number;
  /** @nullable */
  format?: string | null;
  /** @nullable */
  internalProductId?: string | null;
  isActive?: boolean;
  /** @nullable */
  languageCode?: string | null;
  /** @nullable */
  productCategories?: LibraryProductCategory[] | null;
  productType?: number;
  publicationDate?: string;
  /** @nullable */
  publisher?: string | null;
  /** @nullable */
  sampleUri?: string | null;
  /** @nullable */
  thumbnailUri?: string | null;
  /** @nullable */
  title?: string | null;
  updatedUtc?: string;
}
