/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Publizon Library API
 * Pubhub exists in two separate environments, each with their own server, code and database. Please use the web service located at library-api.qa.pubhub.dk when developing and testing.
Orders/loans created in test environment will not be invoiced. Please request a new license key for the production environment when you're ready to go live.
 * OpenAPI spec version: 1
 */

export interface UserData {
  audiobookLoansRemaining?: number;
  audioLoanAvailableUtc?: string;
  ebookLoanAvailableUtc?: string;
  ebookLoansRemaining?: number;
  /** @nullable */
  friendlyCardNumber?: string | null;
  totalAudioLoans?: number;
  totalEbookLoans?: number;
  totalLoans?: number;
}
